#!/usr/bin/env python3

import argparse
import json
import fractions
import sympy
import sys
import pandas
import sklearn.linear_model

parser = argparse.ArgumentParser()
parser.add_argument("--input-file", default="zorgette-catalog.json",
                    help="File generated by create_zorgette_catalogue.py. Should be a list of 3-element lists")
parser.add_argument("--output", help="Where to create a LaTeX file with the equation results")
args = parser.parse_args()

data = pandas.DataFrame(json.load(open(args.input_file)), columns=['x', 'y', 'z'])

ols = sklearn.linear_model.LinearRegression()
ols.fit(data[['y', 'z']], data.x)

y, z = sympy.symbols('y z')
equation = ols.coef_[0] * y + ols.coef_[1] * z + ols.intercept_

if args.output:
    with open(args.output,'w') as f:
        f.write(r'\newcommand{\zorgetteols}[0]{x = ')
        f.write(sympy.latex(equation))
        f.write('}\n')


