name: Run wordnet2padic.py

on:
  push:
    branches:
      - '*'

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run wordnet2padic.py
        run: python wordnet2padic.py
