# Workflow to run wordnet2padic.py
#
# This workflow is triggered on push and pull request events. It sets up the Python environment, installs the necessary packages, and runs the wordnet2padic.py script.
#
# Steps:
# 1. Checkout code
# 2. Set up Python
# 3. Install nltk package and download wordnet dataset
# 4. Run wordnet2padic.py
# 5. Check exit status
#
# If any step fails, the workflow will exit with a non-zero status code.
      - name: Checkout code
        uses: actions/checkout@v2

      

      
