name: Run wordnet2padic.py

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python packages
        run: pip install -r requirements.txt

      - name: Run Makefile
        run: make
        id: script

      - name: Check exit status
        if: ${{ steps.script.outcome != 'success' }}
        run: exit 1
